server:
  port: 9000

spring:
  application:
    name: demo-srv
#  cloud:
#    config:
#      enabled: false
#    nacos:
#      discovery:
#        server-addr: 172.16.2.164:8848
#        username: nacos
#        password: nacos
#      config:
#        server-addr: 172.16.2.164:8848
#        username: nacos
#        password: nacos
#        prefix: mes-service
#        file-extension: yml
  main:
    allow-bean-definition-overriding: true

logging:
  config: classpath:logback.xml
